name: loadtest-max

on: workflow_dispatch

jobs:
  stress-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [1, 2, 3, 4, 5]
    steps:
      - name: Cài hey
        run: sudo apt-get update && sudo apt-get install -y hey

      - name: Bắn 10000 request
        run: hey -z 120s -c 1000 play.langbaton.fun
